#!/usr/bin/env bash
# build-claude-md.sh -- assemble week<N>/CLAUDE.md from prompt-instance + shared sources
# Usage: scripts/build-claude-md.sh <week-number>

set -euo pipefail

WEEK="${1:-}"
if [[ -z "$WEEK" ]]; then
  echo "Usage: $0 <week-number>" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTANCE_DIR="$REPO_ROOT/week$WEEK/prompt-instance"
SHARED_CORE="$REPO_ROOT/shared/prompt-core"
OUTPUT="$REPO_ROOT/week$WEEK/CLAUDE.md"

if [[ ! -d "$INSTANCE_DIR" ]]; then
  echo "Error: $INSTANCE_DIR not found" >&2
  exit 1
fi

mkdir -p "$REPO_ROOT/week$WEEK"

# Required instance files -- identity, philosophy and flow are required for every week
for f in 01-identity.md 02-philosophy.md 07-flow.md; do
  if [[ ! -f "$INSTANCE_DIR/$f" ]]; then
    echo "Error: required instance file missing: $INSTANCE_DIR/$f" >&2
    exit 1
  fi
done

# Required shared/prompt-core files
for f in 01-coaching-rules.md 02-evidence-scales.md 03-founder-nightmares.md 04-nine-fits.md 05-output-conventions.md; do
  if [[ ! -f "$SHARED_CORE/$f" ]]; then
    echo "Error: required shared file missing: $SHARED_CORE/$f" >&2
    exit 1
  fi
done

{
  echo "<!-- Generated by scripts/build-claude-md.sh. Do not edit directly. -->"
  echo "<!-- Edit sources in week$WEEK/prompt-instance/ and shared/ instead. -->"
  echo
  cat "$INSTANCE_DIR/01-identity.md"
  echo
  cat "$INSTANCE_DIR/02-philosophy.md"
  echo
  cat "$SHARED_CORE/01-coaching-rules.md"
  echo
  cat "$SHARED_CORE/02-evidence-scales.md"
  echo
  cat "$SHARED_CORE/03-founder-nightmares.md"
  echo
  cat "$SHARED_CORE/04-nine-fits.md"
  echo
  cat "$SHARED_CORE/05-output-conventions.md"
  echo
  # Exercises (if present) -- Week 3 has 04/05/06-exercise-*.md
  for f in "$INSTANCE_DIR"/[0-9][0-9]-exercise-*.md; do
    [[ -f "$f" ]] || continue
    cat "$f"
    echo
  done
  # Venture stories (Week 3 only)
  if [[ -f "$INSTANCE_DIR/03-venture-stories.md" ]]; then
    cat "$INSTANCE_DIR/03-venture-stories.md"
    echo
  fi
  # Flow
  cat "$INSTANCE_DIR/07-flow.md"
  echo
  # Week 2 legacy extras (optional, included if present)
  for f in "$INSTANCE_DIR/03-coaching-behaviours.md" "$INSTANCE_DIR/06-knowledge-refs.md" "$INSTANCE_DIR/08-output-specs.md"; do
    if [[ -f "$f" ]]; then
      cat "$f"
      echo
    fi
  done
  # Methodology references section
  echo "## Methodology references"
  echo
  echo "Read these files on demand during coaching:"
  echo
  if [[ -d "$REPO_ROOT/shared/prompt-methodology/discovery" ]]; then
    for f in "$REPO_ROOT/shared/prompt-methodology/discovery"/*.md; do
      [[ -f "$f" ]] || continue
      rel="${f#$REPO_ROOT/}"
      echo "- \`$rel\`"
    done
  fi
  if [[ -f "$REPO_ROOT/shared/prompt-methodology/cyber-context.md" ]]; then
    echo "- \`shared/prompt-methodology/cyber-context.md\`"
  fi
  # Week 2 co-located exercise knowledge files
  for base in competition-matrix differentiation-statement personas sales-battlecard solution-one-pager value-proposition; do
    if [[ -f "$INSTANCE_DIR/$base.md" ]]; then
      echo "- \`week$WEEK/prompt-instance/$base.md\`"
    fi
  done
} > "$OUTPUT"

echo "Wrote $OUTPUT ($(wc -l < "$OUTPUT") lines)"
