#!/usr/bin/env bash
# build-web-prompt.sh -- assemble week<N>/web/prompt.md from shared + instance sources
# Produces the non-tech mega-prompt with Part 1 (active brain) / Part 2 (methodology) /
# Part 3 (exercises) / Part 4 (reference).
# Usage: scripts/build-web-prompt.sh <week-number>

set -euo pipefail

WEEK="${1:-}"
if [[ -z "$WEEK" ]]; then
  echo "Usage: $0 <week-number>" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTANCE_DIR="$REPO_ROOT/week$WEEK/prompt-instance"
SHARED_CORE="$REPO_ROOT/shared/prompt-core"
METHODOLOGY_DIR="$REPO_ROOT/shared/prompt-methodology/discovery"
OUTPUT_DIR="$REPO_ROOT/week$WEEK/web"
OUTPUT="$OUTPUT_DIR/prompt.md"

mkdir -p "$OUTPUT_DIR"

# Required instance files for the mega-prompt
for f in 01-identity.md 02-philosophy.md 07-flow.md 08-close.md; do
  if [[ ! -f "$INSTANCE_DIR/$f" ]]; then
    echo "Error: required instance file missing: $INSTANCE_DIR/$f" >&2
    exit 1
  fi
done

# Required shared/prompt-core files
for f in 01-coaching-rules.md 02-evidence-scales.md 03-founder-nightmares.md 04-nine-fits.md 05-output-conventions.md; do
  if [[ ! -f "$SHARED_CORE/$f" ]]; then
    echo "Error: required shared file missing: $SHARED_CORE/$f" >&2
    exit 1
  fi
done

{
  echo "<!-- Generated by scripts/build-web-prompt.sh. Do not edit directly. -->"
  echo
  echo "# Hub201 Week $WEEK Customer Discovery Coach"
  echo
  echo "## Part 1: Your coaching brain (always active)"
  echo
  cat "$INSTANCE_DIR/01-identity.md"
  echo
  cat "$SHARED_CORE/01-coaching-rules.md"
  echo
  cat "$INSTANCE_DIR/07-flow.md"
  echo
  echo "## Part 2: The methodology you teach (consult as needed)"
  echo
  cat "$INSTANCE_DIR/02-philosophy.md"
  echo
  cat "$SHARED_CORE/02-evidence-scales.md"
  echo
  cat "$SHARED_CORE/03-founder-nightmares.md"
  echo
  cat "$SHARED_CORE/04-nine-fits.md"
  echo
  if [[ -d "$METHODOLOGY_DIR" ]]; then
    for f in "$METHODOLOGY_DIR"/*.md; do
      [[ -f "$f" ]] || continue
      cat "$f"
      echo
    done
  fi
  # Cyber context (applies to Hub201)
  if [[ -f "$REPO_ROOT/shared/prompt-methodology/cyber-context.md" ]]; then
    cat "$REPO_ROOT/shared/prompt-methodology/cyber-context.md"
    echo
  fi
  echo "## Part 3: The three exercises (consult when the founder picks one)"
  echo
  for f in "$INSTANCE_DIR"/[0-9][0-9]-exercise-*.md; do
    [[ -f "$f" ]] || continue
    cat "$f"
    echo
  done
  echo "## Part 4: Reference material (consult when relevant)"
  echo
  if [[ -f "$INSTANCE_DIR/03-venture-stories.md" ]]; then
    cat "$INSTANCE_DIR/03-venture-stories.md"
    echo
  fi
  cat "$SHARED_CORE/05-output-conventions.md"
  echo
  cat "$INSTANCE_DIR/08-close.md"
} > "$OUTPUT"

echo "Wrote $OUTPUT ($(wc -l < "$OUTPUT") lines, $(wc -c < "$OUTPUT") bytes)"
